server:
  port: 8003
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.210:3306/tensquare_base?characterEncoding=utf-8
    password: 12345678
    username: root
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.43.217
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true