server:
  port: 9006
spring:
  application:
    name: tensquare‐spit #指定服务名
  data:
    mongodb:
     host: 192.168.43.210
     database: spitdb
  redis:
    host: 192.168.43.210
  rabbitmq:
    host: 192.168.43.210
eureka:
  client:
    service-url:
      defaultZone: http://192.168.43.210:6868/eureka/
  instance:
    prefer-ip-address: true